#################################################################
# +-----------------------------------------------------------+ #
# |                          Identity                         | #
# |                        By MikesLab                        | #
# +-----------------------------------------------------------+ #
#################################################################

#################################################################
# ----------------------- Donations <3 ------------------------ #
# ------------------- donation.mikeslab.it -------------------- #
#################################################################

sentry:
  enabled: true
  dsn: "https://824b6bf15450fd6639da49ad58460e09@o4504045887029248.ingest.us.sentry.io/4507119803039744" # Sentry DSN
database:
  type: SQL # SQL or MONGODB
  uri: "jdbc:sqlite:{dataFolder}/identity.db"
  password: ""
  username: ""
  database: widennetwork
  table: identities

anvil-confirm-item-material: "MAP"
anvil-confirm-item-model-data: 1010

chat-format: "<symbol> <yellow><age> <gray><firstname> <lastname><blue>: <white><message>"

kick-if-saving-error: true

command-aliases: "identity|id"
enable-chat-formatter: true
first-char-uppercase: true

chat-distance: 10 # -1 for unlimited

guis:
  test:
    path: inventories/selector.yml
    type: SELECTOR
    mandatory: true
  main-test:
    path: inventories/main.yml
    type: MAIN